# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gtaxllte/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gtaxllte gtanotexllte,$(TARGET_DEVICE)),)

endif
